services:
  pyspark:
    image: jupyter/pyspark-notebook:x86_64-ubuntu-22.04
    container_name: pyspark_jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      #- ./test_data:/app/test_data
      #- ./test_data:/home/jovyan